### Listar todos los incidents
GET http://localhost:5116/api/incidents
Accept: application/json

### Obtener un incident por id
GET http://localhost:5116/api/incidents/186c2fcc-a926-4602-67d7-08de7c0e3e37
Accept: application/json

### Crear un nuevo incident
POST http://localhost:5116/api/incidents
Content-Type: application/json

{
  "id": "186c2fcc-a926-4602-67d7-08de7c0e3e37",
  "title": "Nueva incidencia de prueba",
  "description": "Esto es solo un test2",
  "status": "Open"
}

### Actualizar un incident
PUT http://localhost:5116/api/incidents/186c2fcc-a926-4602-67d7-08de7c0e3e37
Content-Type: application/json

{
  "id": "186c2fcc-a926-4602-67d7-08de7c0e3e37",
  "title": "Servidor caído - Actualizado",
  "description": "El servidor se restableció parcialmente.",
  "status": "In Progress"
}

### Eliminar un incident
DELETE http://localhost:5116/api/incidents/186c2fcc-a926-4602-67d7-08de7c0e3e37